### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ZoeDepth:

### ISSUE THREAD

**Issue by goometasoft** [okaris/omni-zero-couples#1]
```
windows-10 , cuda-12.1 , pytorch-2.2

python demo.py

Traceback (most recent call last):
  File "E:\AI\A4C\240926\win_121\demo.py", line 39, in <module>
    demo()
  
  File "E:\AI\A4C\240926\win_121\demo.py", line 4, in demo
    omni_zero = OmniZeroCouple(
  
  File "E:\AI\A4C\240926\win_121\omni_zero.py", line 191, in __init__
    self.zoe_depth_detector = ZoeDetector.from_pretrained("lllyasviel/Annotators").to(device)
  
  File "D:\conda\envs\cuda121\lib\site-packages\controlnet_aux-0.0.7-py3.9.egg\controlnet_aux\zoe\__init__.py", line 32, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])
  
  File "D:\conda\envs\cuda121\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.1.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.2.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.3.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.4.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.5.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.6.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.7.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.8.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.9.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.10.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.11.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.12.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.13.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.14.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.15.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.16.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.17.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.18.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.19.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.20.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.21.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.22.attn.relative_position_index", 
		"core.core.pretrained.model.blocks.23.attn.relative_position_index".
```

**Comment by okaris** [comment]
Hi, did you install the requirements file. I remember seeing this issue when the diffusers library was an older version
