### ISSUE TITLE
Get error in tokenizer

### ISSUE THREAD

**Issue by YoucanBaby** [okaris/omni-zero-couples#3]
```
Traceback (most recent call last):
  File "/ssd1/xyf/personalization/animation/omni-zero-couples/demo.py", line 44, in <module>
    demo()
  File "/ssd1/xyf/personalization/animation/omni-zero-couples/demo.py", line 19, in demo
    images = omni_zero.generate(
  File "/ssd1/xyf/personalization/animation/omni-zero-couples/omni_zero.py", line 348, in generate
    images = self.pipeline(
  File "/ssd1/anaconda3/envs/zbx_instant/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/ssd1/xyf/personalization/animation/omni-zero-couples/pipeline.py", line 1494, in __call__
    ) = self.encode_prompt(
  File "/ssd1/xyf/personalization/animation/omni-zero-couples/pipeline.py", line 460, in encode_prompt
    prompt = self.maybe_convert_prompt(prompt, tokenizer)
  File "/ssd1/anaconda3/envs/zbx_instant/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 135, in maybe_convert_prompt
    prompts = [self._maybe_convert_prompt(p, tokenizer) for p in prompts]
  File "/ssd1/anaconda3/envs/zbx_instant/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 135, in <listcomp>
    prompts = [self._maybe_convert_prompt(p, tokenizer) for p in prompts]
  File "/ssd1/anaconda3/envs/zbx_instant/lib/python3.10/site-packages/diffusers/loaders/textual_inversion.py", line 158, in _maybe_convert_prompt
    tokens = tokenizer.tokenize(prompt)
AttributeError: 'NoneType' object has no attribute 'tokenize'
```

**Comment by okaris** [comment]
Hi there! 👋

It looks like there might be an issue with the version of the `diffusers` library you're using. Could you please double-check the version by running this command in your environment?

```bash
pip show diffusers
```

If it's not installed or outdated, make sure to install the required dependencies from the `requirements.txt` file. You can do this by running:

```bash
pip install -r requirements.txt
```

Alternatively, you can update the `diffusers` package directly using:

```bash
pip install --upgrade diffusers
```

Let me know if that helps!

**Comment by YoucanBaby** [comment]
> Hi there! 👋
> 
> It looks like there might be an issue with the version of the `diffusers` library you're using. Could you please double-check the version by running this command in your environment?
> 
> ```shell
> pip show diffusers
> ```
> 
> If it's not installed or outdated, make sure to install the required dependencies from the `requirements.txt` file. You can do this by running:
> 
> ```shell
> pip install -r requirements.txt
> ```
> 
> Alternatively, you can update the `diffusers` package directly using:
> 
> ```shell
> pip install --upgrade diffusers
> ```
> 
> Let me know if that helps!

![image](https://github.com/user-attachments/assets/55ebd73a-d6f7-4799-addb-1e2ff2e273d0)

`diffusers` is 0.30.3

**Comment by YoucanBaby** [comment]
I fix this error by not using `.safetensors`

It seems that `https://huggingface.co/frankjoshua/albedobaseXL_v13/blob/main/albedobaseXL_v13.safetensors` lose `text_encoder_2`.

**Comment by YoucanBaby** [comment]
> Hi there! 👋
> 
> It looks like there might be an issue with the version of the `diffusers` library you're using. Could you please double-check the version by running this command in your environment?
> 
> ```shell
> pip show diffusers
> ```
> 
> If it's not installed or outdated, make sure to install the required dependencies from the `requirements.txt` file. You can do this by running:
> 
> ```shell
> pip install -r requirements.txt
> ```
> 
> Alternatively, you can update the `diffusers` package directly using:
> 
> ```shell
> pip install --upgrade diffusers
> ```
> 
> Let me know if that helps!

Thanks a lot for your patient reply!
And thanks for your great project!
